# Generated by Django 4.2.4 on 2024-03-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cart_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='size',
        ),
    ]
